### ISSUE TITLE
Add requirements file with package dependencies

### ISSUE THREAD

**Issue by Priyansh-Kedia** [unmtransinfo/cfde-distillery#10]
Issue: While setting up the environment to run the code files, you need to manually install the packages (like pandas and numpy) using pip (or conda). 

Possible Issues: This can lead to issues if the package is updated, and the code is written specific to some previous version

Solution: To add a requirements.txt file in the code. To install the dependencies, only need to install the ones mentioned in the file

**Comment by Priyansh-Kedia** [comment]
@pkumar81 please let me know what you think about this

**Comment by pkumar81** [comment]
We can add requirements.txt. However, since these codes are used by only our team, we should update them whenever there is any change in any Python package.

**Comment by Priyansh-Kedia** [comment]
That makes sense, thanks
I will add a requirements file for the project
